name: impact-synergy
channels:
  - conda-forge
dependencies:
  - python=3.8.12
  - pip=21.2.4
  - numpy=1.21.2
  - pandas=1.3.5
  - scipy=1.7.1
  - scikit-learn=1.0.2
  - statsmodels=0.13.2
  - nibabel=3.2.2
  - nilearn=0.9.2
  - pybids=0.14.2
  - networkx=2.6.3
  - python-louvain=0.15
  - python-docx=0.8.11
  - matplotlib=3.4.3
  - joblib=1.1.0
  - scikit-bio=0.5.6
  - pytest=6.2.4
  - bids-validator=1.7.4
  - flake8=4.0.1
  - black=22.3.0
  - pre-commit
