name: impact-synergy
channels:
  - conda-forge
dependencies:
  - python=3.8
  - scikit-bio=0.5.6
  - numpy=1.21
  - pandas=1.3
  - scipy=1.7
  - scikit-learn=1.0
  - statsmodels=0.13
  - nibabel=3.2
  - nilearn=0.9
  - networkx=2.6
  - python-louvain=0.15
  - python-docx=0.8
  - matplotlib=3.4
  - joblib=1.1
  - pytest=6.2
  - flake8=4.0
  - black=22.3
  - pip
  - pip:
      - pybids==0.14.1
      - bids-validator==1.7.3



