name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          activate-environment: impact-synergy

      # ensure flake8/black are present
      - name: Install lint tools
        run: conda install -y flake8 black

      - name: Lint
        run: |
          flake8 .
          black --check .

      - name: Test
        run: pytest -q --disable-warnings --maxfail=1
